# Generated by Django 5.2.17 on 2026-09-19 19:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("normalized_name", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="package_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="package_unit_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("g", "gram"),
                    ("kg", "kilogram"),
                    ("ml", "mililitr"),
                    ("l", "litr"),
                    ("szt", "sztuka"),
                    ("opak", "opakowanie"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("package_quantity__isnull", True), ("package_unit_code", "")),
                    models.Q(
                        ("package_quantity__isnull", False),
                        models.Q(("package_unit_code", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="product_package_quantity_requires_unit",
            ),
        ),
        migrations.AddField(
            model_name="productalias",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                to="households.product",
            ),
        ),
        migrations.AddIndex(
            model_name="productalias",
            index=models.Index(fields=["normalized_name"], name="households__normali_c2bc79_idx"),
        ),
        migrations.AddConstraint(
            model_name="productalias",
            constraint=models.UniqueConstraint(
                fields=("product", "normalized_name"), name="unique_alias_per_product"
            ),
        ),
    ]
