# Generated by Django 5.2.17 on 2026-09-20 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("households", "0002_productalias_product_package_quantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientAliasProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("requirement_name", models.CharField(max_length=120)),
                ("normalized_requirement_name", models.CharField(max_length=120)),
                ("model_name", models.CharField(max_length=80)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alias_proposals",
                        to="households.household",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alias_proposals",
                        to="households.product",
                    ),
                ),
            ],
            options={
                "ordering": ["household_id", "requirement_name", "id"],
                "indexes": [
                    models.Index(
                        fields=["household", "state"], name="households__househo_c11ac6_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("household", "normalized_requirement_name", "product"),
                        name="unique_alias_proposal_pair",
                    )
                ],
            },
        ),
    ]
