# Generated by Django 5.2.17 on 2026-09-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PromotionAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "permissions": [("view_promotions", "Can view promotions")],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
