# Generated by Django 5.2.17 on 2026-09-19 08:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_lists",
                        to="households.household",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PrimaryShoppingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "household",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_shopping_list",
                        to="households.household",
                    ),
                ),
                (
                    "shopping_list",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_marker",
                        to="shopping.shoppinglist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchasedShoppingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("free_text", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "unit_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("g", "gram"),
                            ("kg", "kilogram"),
                            ("ml", "mililitr"),
                            ("l", "litr"),
                            ("szt", "sztuka"),
                            ("opak", "opakowanie"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("purchased_at", models.DateTimeField()),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchased_shopping_items",
                        to="households.product",
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchased_items",
                        to="shopping.shoppinglist",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["shopping_list", "purchased_at"],
                        name="shopping_pu_shoppin_9da227_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("free_text__isnull", True), ("product__isnull", False)),
                            models.Q(("free_text__isnull", False), ("product__isnull", True)),
                            _connector="OR",
                        ),
                        name="purchased_shopping_item_product_xor_free_text",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ShoppingListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("free_text", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "unit_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("g", "gram"),
                            ("kg", "kilogram"),
                            ("ml", "mililitr"),
                            ("l", "litr"),
                            ("szt", "sztuka"),
                            ("opak", "opakowanie"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shopping_list_items",
                        to="households.product",
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shopping.shoppinglist",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("free_text__isnull", True), ("product__isnull", False)),
                            models.Q(("free_text__isnull", False), ("product__isnull", True)),
                            _connector="OR",
                        ),
                        name="shopping_item_product_xor_free_text",
                    ),
                    models.UniqueConstraint(
                        fields=("shopping_list", "product"),
                        name="unique_pending_shopping_item_product",
                    ),
                ],
            },
        ),
    ]
