# Generated by Django 5.2.17 on 2026-09-18 19:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_base_measurement_units"),
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_lists",
                        to="households.household",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("free_text", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_purchased", models.BooleanField(default=False)),
                ("purchased_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shopping_list_items",
                        to="catalog.ingredient",
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shopping.shoppinglist",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shopping_list_items",
                        to="catalog.measurementunit",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="shoppinglist",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("household",),
                name="unique_primary_shopping_list_per_household",
            ),
        ),
        migrations.AddIndex(
            model_name="shoppinglistitem",
            index=models.Index(
                fields=["shopping_list", "is_purchased"], name="shopping_sh_shoppin_0e13e4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shoppinglistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("free_text__isnull", True), ("ingredient__isnull", False)),
                    models.Q(("free_text__isnull", False), ("ingredient__isnull", True)),
                    _connector="OR",
                ),
                name="shopping_item_ingredient_xor_free_text",
            ),
        ),
        migrations.AddConstraint(
            model_name="shoppinglistitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ingredient__isnull", False), ("is_purchased", False)),
                fields=("shopping_list", "ingredient"),
                name="unique_unpurchased_shopping_item_ingredient",
            ),
        ),
    ]
