# Generated by Django 5.2.17 on 2026-09-19 05:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_base_measurement_units"),
        ("households", "0001_initial"),
        ("shopping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrimaryShoppingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "household",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_shopping_list",
                        to="households.household",
                    ),
                ),
                (
                    "shopping_list",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_marker",
                        to="shopping.shoppinglist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchasedShoppingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("free_text", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("purchased_at", models.DateTimeField()),
                (
                    "ingredient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchased_shopping_items",
                        to="catalog.ingredient",
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchased_items",
                        to="shopping.shoppinglist",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchased_shopping_items",
                        to="catalog.measurementunit",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["shopping_list", "purchased_at"],
                        name="shopping_pu_shoppin_9da227_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("free_text__isnull", True), ("ingredient__isnull", False)),
                            models.Q(("free_text__isnull", False), ("ingredient__isnull", True)),
                            _connector="OR",
                        ),
                        name="purchased_shopping_item_ingredient_xor_free_text",
                    )
                ],
            },
        ),
    ]
