# Generated by Django 5.2.17 on 2026-09-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_base_measurement_units"),
        ("shopping", "0003_move_primary_and_purchased_rows"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shoppinglist",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveConstraint(
            model_name="shoppinglist",
            name="unique_primary_shopping_list_per_household",
        ),
        migrations.RemoveConstraint(
            model_name="shoppinglistitem",
            name="unique_unpurchased_shopping_item_ingredient",
        ),
        migrations.RemoveIndex(
            model_name="shoppinglistitem",
            name="shopping_sh_shoppin_0e13e4_idx",
        ),
        migrations.RemoveField(
            model_name="shoppinglist",
            name="is_primary",
        ),
        migrations.RemoveField(
            model_name="shoppinglistitem",
            name="is_purchased",
        ),
        migrations.RemoveField(
            model_name="shoppinglistitem",
            name="purchased_at",
        ),
        migrations.AddConstraint(
            model_name="shoppinglistitem",
            constraint=models.UniqueConstraint(
                fields=("shopping_list", "ingredient"),
                name="unique_pending_shopping_item_ingredient",
            ),
        ),
    ]
